### ISSUE TITLE
Query with 1 result is out of sequence

### ISSUE THREAD

**Issue by JohnnyPicnic** [sungkhum/MicroPyDatabase#6]
When I query a table with just 1 result I get the following:

`{'r': 1, 'd': {'time': '23/01/27_11:32:12', 'data': '1', 'temperature': 20.95853}}`

If I add another row then the results are as expected:
`{'time': '23/01/27_11:32:12', 'data': '1', 'temperature': 20.95853}
{'time': '23/01/27_11:36:37', 'data': '1', 'temperature': 21.89482}`

**Comment by JohnnyPicnic** [comment]
Attached is my code:

Database Create Success
Database Open Success
Temperature Table Create Success
Inserted First Temperature Dummy Row
[{'r': 1, 'd': {'time': '99/01/01_01:00:00', 'data': '1', 'temperature': '0'}}]

[tabletest.txt](https://github.com/sungkhum/MicroPyDatabase/files/10547153/tabletest.txt)

**Comment by lixas** [comment]
Yes, there is a bug.
https://github.com/sungkhum/MicroPyDatabase/blob/4cb4ac1becf4518aca939a0d407ca607efcf8817/micropydatabase.py#L400
I'll fix it in my own fork and I hope author will accept pull request for this fix and more enhancements

**Comment by JohnnyPicnic** [comment]
Thank you!

**Comment by lixas** [comment]
looks like quick'n'dirty fix could be modify else statement in query function to following:

    def query(self, queries: dict):
        """
        Search through the whole table and return all rows where column
        data matches searched for value.
        """
        final_result = []
        results = self.__return_query('query', queries)
        if results is None:
            return None
        else:
            for result in results:
                final_result.append(result['d'])
        return final_result

This way you'll have consistency- as a result you should have list of dict's

**Comment by sungkhum** [comment]
@lixas I merged the current pull requests - let me know if there are any more. Thanks for the fixes!

**Comment by JohnnyPicnic** [comment]
Removing the `if len(results) > 1:` from query seems to work.
Thank you.

**Comment by lixas** [comment]
fixed result consistency in https://github.com/sungkhum/MicroPyDatabase/pull/7
